In [12]:
import pandas as pd
import numpy as np

In [2]:
import tensorflow as tf

2024-09-14 09:00:36.217241: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
###  exp sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
## Define the Vocab Size
voc_size=10000

In [7]:
##  one hot representation

one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr 

[[3844, 3148, 6662, 7607],
 [3844, 3148, 6662, 4626],
 [3844, 6007, 6662, 6906],
 [9692, 9455, 3093, 7717, 3419],
 [9692, 9455, 3093, 7717, 9464],
 [8584, 3844, 2458, 6662, 5032],
 [595, 3477, 1776, 7717]]

These all the indexes are shown         
there some problem are there so we will use these indexs

In [11]:
## Now we will take all words sentece by sentence and pass through the enbedding layer
 
## word Enbedding Representation

from tensorflow.keras.layers import Embedding
##from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential



in our sentence list some of them have 4 words some 5 words to passes through we need to have a fixed size for that the pad_sequences will work

we are setting a length words of 8 

In [13]:
sent_length= 8
embedded_docs= pad_sequences(one_hot_repr, padding='pre',maxlen=sent_length)
embedded_docs  ## padding='pre' if we write post then the o will add in the last

array([[   0,    0,    0,    0, 3844, 3148, 6662, 7607],
       [   0,    0,    0,    0, 3844, 3148, 6662, 4626],
       [   0,    0,    0,    0, 3844, 6007, 6662, 6906],
       [   0,    0,    0, 9692, 9455, 3093, 7717, 3419],
       [   0,    0,    0, 9692, 9455, 3093, 7717, 9464],
       [   0,    0,    0, 8584, 3844, 2458, 6662, 5032],
       [   0,    0,    0,    0,  595, 3477, 1776, 7717]], dtype=int32)

In [14]:
## feature representation 

dim=10  ## we are taking this as dimention in study we take 300 dimention


In [15]:
## prepaering the model for compileing the sentences which we have
model= Sequential()
model.add(Embedding(voc_size,dim, input_length=sent_length))
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
## predicted as word embedding
model.predict(embedded_docs)

1/1 [==============================] - 0s 22ms/step


array([[[ 0.00264989, -0.04390817, -0.02665962,  0.04271128,
          0.02591333,  0.003157  , -0.0015354 , -0.04173166,
         -0.02360705,  0.04191423],
        [ 0.00264989, -0.04390817, -0.02665962,  0.04271128,
          0.02591333,  0.003157  , -0.0015354 , -0.04173166,
         -0.02360705,  0.04191423],
        [ 0.00264989, -0.04390817, -0.02665962,  0.04271128,
          0.02591333,  0.003157  , -0.0015354 , -0.04173166,
         -0.02360705,  0.04191423],
        [ 0.00264989, -0.04390817, -0.02665962,  0.04271128,
          0.02591333,  0.003157  , -0.0015354 , -0.04173166,
         -0.02360705,  0.04191423],
        [ 0.00562809,  0.01874361, -0.0433224 ,  0.0060956 ,
         -0.02211093, -0.01831878,  0.01151104, -0.01508169,
         -0.02108302,  0.04123933],
        [ 0.01344544, -0.04267393,  0.02934175,  0.03861009,
          0.0196299 , -0.01725626,  0.0262459 , -0.01706761,
         -0.04846631,  0.02962359],
        [ 0.04314   , -0.04646008,  0.0075805 ,  0.0

In [21]:
embedded_docs[0]

array([   0,    0,    0,    0, 3844, 3148, 6662, 7607], dtype=int32)

In [22]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 43ms/step


array([[ 0.00264989, -0.04390817, -0.02665962,  0.04271128,  0.02591333,
         0.003157  , -0.0015354 , -0.04173166, -0.02360705,  0.04191423],
       [ 0.00264989, -0.04390817, -0.02665962,  0.04271128,  0.02591333,
         0.003157  , -0.0015354 , -0.04173166, -0.02360705,  0.04191423],
       [ 0.00264989, -0.04390817, -0.02665962,  0.04271128,  0.02591333,
         0.003157  , -0.0015354 , -0.04173166, -0.02360705,  0.04191423],
       [ 0.00264989, -0.04390817, -0.02665962,  0.04271128,  0.02591333,
         0.003157  , -0.0015354 , -0.04173166, -0.02360705,  0.04191423],
       [ 0.00562809,  0.01874361, -0.0433224 ,  0.0060956 , -0.02211093,
        -0.01831878,  0.01151104, -0.01508169, -0.02108302,  0.04123933],
       [ 0.01344544, -0.04267393,  0.02934175,  0.03861009,  0.0196299 ,
        -0.01725626,  0.0262459 , -0.01706761, -0.04846631,  0.02962359],
       [ 0.04314   , -0.04646008,  0.0075805 ,  0.0184014 ,  0.03588757,
         0.0321687 , -0.03447897, -0.04767285